name: owncast
adopt-info: owncast
summary: Take control over your content and stream it yourself.
description: |
  Take control over your content and stream it yourself.

license: MIT

base: core20
grade: stable 
confinement: strict

architectures:
  - build-on: amd64

apps:
  owncast:
    command: $SNAP/bin/main.go
    plugs:
      - home
      - network
      - network-bind

  owncast:
    source: https://github.com/owncast/owncast
    source-type: git
    plugin: go
    go-import-path: github.com/owncast/owncast
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
          
    stage-packages:
      - libslang2
      - freeglut3 
      - libglu1-mesa   
      - ffmpeg
    
