name: owncast
adopt-info: owncast
summary: Take control over your content and stream it yourself.
description: |
  Take control over your content and stream it yourself.

license: MIT
issues: https://github.com/owncast/owncast/issues
source-code: https://github.com/owncast/owncast
contact: https://github.com/owncast/owncast
base: core24
grade: stable 
confinement: devmode
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  
apps:
  owncast:
    command: bin/owncast
    plugs:
      - home
      - network
      - network-bind
      - pulseaudio
      - alsa
      
parts:
  owncast:
    source: https://github.com/owncast/owncast
    source-type: git
    plugin: go
          
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
          
    stage-packages:
      - libslang2
      - freeglut3 
      - libglu1-mesa
      - golang
      - ffmpeg
