name: owncast
adopt-info: owncast
summary: Take control over your content and stream it yourself.
description: |
  Take control over your content and stream it yourself.

license: MIT
issues: https://github.com/owncast/owncast/issues
source-code: https://github.com/owncast/owncast
contact: https://github.com/owncast/owncast
base: core22
grade: stable 
confinement: devmode
compression: lzo

architectures:
  - build-on: amd64
  
apps:
  owncast:
    command: launch
    plugs:
      - home
      - network
      - network-bind
      - pulseaudio
      - alsa
      
parts:
  owncast:
    source: https://github.com/owncast/owncast
    source-type: git
    plugin: nil

    override-build: |
      mkdir -p BUILD
      cd BUILD/
      git clone https://github.com/owncast/owncast
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r * $CRAFT_PART_INSTALL/bin/
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
    
    build-snaps:
      - go/latest/edge
    
    stage-snaps:
      - go/latest/edge 
    
    stage-packages:
      - libslang2
      - freeglut3 
      - libglu1-mesa
      - ffmpeg

  launcher:
    plugin: dump
    source: scripts
