name: owncast
adopt-info: owncast
summary: Take control over your content and stream it yourself.
description: |
  Take control over your content and stream it yourself.

license: MIT
issues: https://github.com/kz6fittycent/owncast/issues
source-code: https://github.com/owncast/owncast
contact: https://github.com/kz6fittycent/owncast
icon: snap/local/owncast.png

base: core24
grade: stable 
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  owncast:
    command: bin/owncast/owncast
    daemon: simple
    restart-condition: always
    plugs:
      - home
      - network
      - network-bind
      - pulseaudio
      - alsa
      
parts:
  owncast:
    source: https://github.com/owncast/owncast
    source-type: git
    plugin: nil

    override-build: |
      mkdir -p BUILD
      cd BUILD/
      curl -s https://owncast.online/install.sh | bash
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r * $CRAFT_PART_INSTALL/bin/
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
    
    build-snaps:
      - go/latest/edge
    
    stage-snaps:
      - go/latest/edge 
      
    build-packages:
      - curl
      - unzip
      
    stage-packages:
      - libslang2
      - freeglut3-dev
      - libglu1-mesa
      - ffmpeg
